# 3个提供者端口分别为8001,8002,8003
server:
  port: 8001
mybatis:
  type-aliases-package: com.mkl.api.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
spring:
  application:
    # 三个都修改为sc-provider-dept，保持一致
    name: sc-provider-dept
  # 数据库分别为db01,db02.db03
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  # 分别为8001,8002,8003
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001 # 这个是修改eureka上status状态栏的默认描述信息

info:
  app.name: mkl-springcloud
  company.name: mkl
  author.name: mkl
