server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
info:
  app.name: sc-mkl
  company.name: mkl
zuul:
  routes:
    # 原本要访问sc-provider-dept的微服务，现在只需要通过/mydept/**来访问
    mydept.serviceId: sc-provider-dept
    mydept.path: /mydept/**
  ignored-services: "*" # 隐藏全部，不能通过微服务名作为路径访问了
  prefix: /mkl # 添加统一访问前缀
